manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: badjeff
      url-base: https://github.com/badjeff

  projects:
    # Base ZMK (badjeff fork, includes extra features youâ€™ve been using)
    - name: zmk
      remote: badjeff
      revision: main
      import: app/west.yml

    # Sensor drivers
    - name: zmk-paw3395-driver
      remote: badjeff
      revision: main
    - name: zmk-pmw3610-driver
      remote: badjeff
      revision: main

    # Input processors / behaviors used in your keymap
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      revision: main
    - name: zmk-behavior-mouse-key-toggle
      remote: badjeff
      revision: main

  self:
    path: config
